### ISSUE TITLE
Consider crediting the original work

### ISSUE THREAD

**Issue by lexisother** [Milkshiift/GoofCord#1]
You have licensed your work under the terms of the OSL. This states the following:

> ```
> 3) Grant of Source Code License. The term "Source Code" means the preferred
> form of the Original Work for making modifications to it and all available
> documentation describing how to modify the Original Work. Licensor agrees to
> provide a machine-readable copy of the Source Code of the Original Work along
> with each copy of the Original Work that Licensor distributes. Licensor
> reserves the right to satisfy this obligation by placing a machine-readable
> copy of the Source Code in an information repository reasonably calculated to
> permit inexpensive and convenient access by You for as long as Licensor
> continues to distribute the Original Work.
> ```

as well as:

> ```
> 6) Attribution Rights. You must retain, in the Source Code of any Derivative
> Works that You create, all copyright, patent, or trademark notices from the
> Source Code of the Original Work, as well as any notices of licensing and any
> descriptive text identified therein as an "Attribution Notice." You must cause
> the Source Code for any Derivative Works that You create to carry a prominent
> Attribution Notice reasonably calculated to inform recipients that You have
> modified the Original Work.
> ```

Your work is clearly a derivate of ArmCord, proven by both the fact this repository used to be a fork (see image) and the fact that the source code is identical.
![image](https://user-images.githubusercontent.com/54973868/226607914-6fee46a4-6334-44cc-a3fb-6f089ec2fd12.png)

Currently, you are failing to comply with the license terms. We as ArmCord have all rights to take action if you fail to comply with the terms of the license.

I recommend following the terms.

**Comment by Milkshiift** [comment]
Thank you for bringing this to my attention. I planned to work on readme later, so I had not yet included the proper attribution notices required by the OSL. I apologize for any inconvenience caused by my oversight.

Moving forward, I will make sure that the source code for any derivative works that I create carries a prominent attribution notice that informs users that I have modified the original work.

Again, I apologize for any confusion or inconvenience caused by my failure to comply with the OSL license terms. I appreciate you bringing this matter to my attention, and I am committed to taking the necessary steps to ensure that I am in full compliance with the license going forward.

**Comment by lexisother** [comment]
Absolutely no problem. I am glad you're willing to work on it.

I'll leave the issue open until concerns are resolved, so you can ask any questions may you have the need.

**Comment by Milkshiift** [comment]
Updated the readme. Let me know if there is anything else I can do.

**Comment by lexisother** [comment]
Seems to be cleared up according to the License.
