### ISSUE TITLE
[BUG] Input fields losing value after settings close

### ISSUE THREAD

**Issue by cd-FileX** [Milkshiift/GoofCord#36]
- [X] I have searched and found no existing issues on the same topic

### Description
Any value written into the input fields in the goofcord settings will be lost once the settings window is closed. 

### Steps to Reproduce
1. Open Goofcord settings
2. Enter a value into e.g. Encryption password
3. Close the settings 
4. Reopen settings

### Expected Behavior
Automatically saved or per button (warning)

### Actual Behavior
Discarded

### Environment
- Operating System (name and version): Kubuntu 24.10
- CPU Architecture (e.g. x64): x64
- GoofCord Version: 1.5.1

### Additional Information

**Comment by Milkshiift** [comment]
I'm not sure if saving text fields when for example a new character is typed is a good solution. 
Saving settings is a heavy operation because of writing to disk, and I would imagine that on a slower machine, previous field state would not have enough time to save before the next character is typed, causing race conditions. 
Settings saving also has feedback in the form of titlebar flashing. If the feedback was not there, the user knows their settings weren't saved. That's the intention, at least.
I think that with the titlebar flashing, the current implementation is intuitive enough.

See https://github.com/Milkshiift/GoofCord/issues/33 for encryption passwords not saving.
