### ISSUE TITLE
[BUG] Clicking on a discord Invites via browser doesn't open the invite in Goofcord

### ISSUE THREAD

**Issue by nyabinary** [Milkshiift/GoofCord#45]
- [X] I have searched and found no existing issues on the same topic
- [X] I have searched the [wiki](https://github.com/Milkshiift/GoofCord/wiki/FAQ) and found no mention of my problem

### Description
Clicking on a Discord link on the browser doesn't open the Discord invite link in Goofcord.
### Steps to Reproduce
Click on a Discord invite on your preferred web browser (in my case, Firefox)
### Expected Behavior
Clicking on the Discord invite will open Goofcord and then ill be able to accept the invitation there.
### Actual Behavior
Doesn't do anything, :P just asks me to login into web discord
### Environment
- Operating System (name and version): NixOS unstable, kernel: 6.10.3
- GoofCord Version: 1.6.0

### Additional Information
GNOME 46

**Comment by notro636** [comment]
This is most likely a talking method between the "web app" and the invite.

![image](https://github.com/user-attachments/assets/df02ff37-9f65-4902-8a3a-af02a566b721)
---
I did a compare between GoofCord, and Vesktop to the official discord app (all are flatpaks), and it did not seem like the differences would prevent this from occurring, so it might've been between the talking of the Discord API, and the app itself, and because of the privacy-focused nature of GoofCord, this may not be possible.

**Comment by Milkshiift** [comment]
Added in https://github.com/Milkshiift/GoofCord/commit/4840596977dcb8fba2f4ce47d86e12edba2cce27
