### ISSUE TITLE
[MISC] Project uses some assets from WebCord

### ISSUE THREAD

**Issue by SpacingBat3** [Milkshiift/GoofCord#68]
> [!NOTE]
> Before you get a heart attack that I might DCMA you for sth, calm down. This is more informative issue than the call to change anything. Even though there still might be some violations of the copyright that put this project in rather *gray* zone of legality.

### Description

From screenshots, I've noticed that this project resembles the look / design of what WebCord uses for *settings* window (this is fine, I'm not as crazy as to even think about suing people for that 😄). However, there are some assets that are clearly copy-pasted from the WebCord project, which is a violation of MIT license (since you need to provide them with at least 2 paragraphs of the software license).

Technically, if you want to comply with the license, you need to provide it, so others know that these assets rely on different licensing terms, and that you are not the original author of them (keeping attribution of that stuff should be important, and MIT is what grants me the actual legal power to do so).

Currently, I've found these files to be used here from my repository:

- [<img src="/SpacingBat3/WebCord/blob/master/sources/assets/icons/symbols/checkmark.svg?raw=true" height=16px> `sources/assets/icons/symbols/checkmark.svg`](/SpacingBat3/WebCord/blob/master/sources/assets/icons/symbols/checkmark.svg)

Honestly, given there isn't anything (at least right now) listed here I would find important, and I'd be rather ashamed of that *checkmark* image I made (I literally draw it quickly on my own to not to use any copyrighted asset), I don't plan going as far as DCMA'ing the project for copyright violation. Either way, you might not trust my words (they don't have any legal power) and provide the license anyway (probably the sanest way would be to add some `MD` file or sth as a doc that lists third-party licenses of software used within this project). As of myself, I think adding some info to the *readme* file near *credits* would be enough for me if you think of a compact way of giving the attribution (take note without providing the license this still violates WebCord's copyright, so it might not be the desired option for you due to that). If you leave it as-is, I don't plan to intervene further, at least for now. I'd personally recommend drawing it on your own and optimizing it yourself, to get your own assets and make sure you have some stuff that isn't really copyrighted in any way. As of me, I could re-consider publishing all `symbols/` from WebCord to the public domain if needed, it's not like I'm proud of how they're made, maybe I could be a bit more proud of optimizing the size they use for some scenarios.

For those who find it absurd to copyright simple shapes and glyphs, apparently [some sites](https://www.flaticon.com/free-icon/check_3388530?term=check+mark&page=1&position=5&origin=tag&related_id=3388530) are doing this for ages. I'm not sure how you can protect derivative work like this in practice (i.e. people vectorizing stuff and slightly modifying the shape, then claiming they drawn this on their own), but yeah, I'm more than sure protecting byte-perfect work would be much simpler.

As final words, I want to remind anyone that licensing stuff on MIT terms is not the same as publishing it to the public domain. There are still some rules you need to follow, even if you license your software / code differently. Please just remember this, if not for making your software *legal* to actually give some attribution to people who sweat a bit on their work (this one might not be the best example 😅).

**Comment by Wuemeli** [comment]
Maybe tell your Bot next time to look into the README File

**Comment by Xephier102** [comment]
> Getting a copyright notice for a checkmark icon was not on my bingo card for GoofCord 😄 My apologies for not properly attributing your work. The [settings' CSS](https://github.com/Milkshiift/GoofCord/blob/main/assets/css/settings.css) that contains the checkbox icon actually includes an, albeit minimal, source credit. I could add a proper attribution, but I thought it would be better to just use a different checkmark [9c84bd4](https://github.com/Milkshiift/GoofCord/commit/9c84bd4ff931060246d46cc9df439261d553bbb6)
> 
> Now, as for the CSS itself, I'm unsure if I need to include the _full_ MIT license. It was originally copy pasted from WebCord, but now there is probably ~5% of the original code left mostly in the :root for colors and input types.

A viral game called Palworld got away with borrowing countless concepts from the Pokemon franchise by cleverly altering them just enough that they didn't fit the legal criteria for a lawsuit. 

What I would recommend if using assets from others (especially a small amount like 5%), is to either use IMG2IMG in a program like ComfyUI or SD Next, to alter any visual components (IE: GUI) to be just a bit different from the original (while perhaps even adding your own personalized twist to it).

Or in terms of code, you could feed it into a chatbot like ChatGPT or Blackbox AI, and tell it to give you back an altered version of the code that does the exact same thing, but is different enough to evade potential lawsuits. If you've been coding for some time, you may even have your own personal style of coding that you could describe to the chatbot to get it to churn out code that would be indiscernible from your own.

**Comment by SpacingBat3** [comment]
> A viral game called Palworld got away with borrowing countless concepts from the Pokemon franchise by cleverly altering them just enough that they didn't fit the legal criteria for a lawsuit.

Honestly, each country might have their own laws around this. But copyrighting the concept by itself is somewhat hard to be done legally for some and doesn't feel ethical at all. Imagine other programs made to do something similar like music editors being copyrighted by someone actually implementing it first.

> (…) is to either use IMG2IMG in a program like ComfyUI or SD Next

> Or in terms of code, you could feed it into a chatbot like ChatGPT or Blackbox AI, (…)

I really despice those concepts. Those are both unethical and illegal if proven to be the case, since you're still relying one someone else's work and sweat as a source material. And even some alterations might be proven as derivative with enough materials from the original author, especially if you by yourself lack any kind of source material (e.g. the vector graphics you were using isn't actually original source, I have vector with the metadata that could be transformed to this state if needed).

What I myself actually doing and recommend to do when I need some non-copyrighted asset is simple: I either use something non-copyrighted public domain asset (doesn't happen often tbh) or just make it yourself. The same goes with the code. A lot of that stuff even has the traced history of changes, so it's easy to prove for me it's mine. Plus, it's fully ethical, since it's my sweat I had to pour into this.

That being said, this thread goes really off-topic, and it's not like I'd call colors used in CSS to be copyrighted 😅. Plus, some effort was made to use original content, so here's that. I still put this thread more in a way as a warning than the action to take down any kind of the assets, to prove I'm not the kind of person to let my work being just re-labeled under someone else's brand. A lot of people thinks you can do this without consequences. Or misread that MIT gives you the right to do anything unconditionaly. Nope, that's not how it works here.

**Comment by SpacingBat3** [comment]
Also, the same goes with the content someone else's doing a PR to your repo – I had a once a scenario someone copy-pasted a code from `@electron` and wanted to push it to one of my projects. I couldn't accept something like this, even if it would be GPTfied or whatever transformation was done to it. So please take care about this, and take some stuff with a bit of grain of salt if you care about not violating others' work licensing terms and conditions that could give you some headache in the future.

**Comment by Xephier102** [comment]
> and doesn't feel ethical at all

On that much, we agree. IMHO, copyrighting should exist solely to protect young business entrepreneurs, not to help large soulless corporations maintain monopolies over entire industries (IE: Nvidia over AI via CUDA).

That said, it should have a 5-10 year maximum soft-limit; after which, other companies are free to use it but just have to pay you X% of overhead profits gained from the use of your IP.

Beyond that, no business large enough to classify as a corporation(or any partner, subsidiary, or shell company/organization/charity of a corporation), should be able to attain a copyright in anything. If you have billions of dollars, you've already won at life; time to give someone else a chance. 

We're always told that capitalism is built on competition, but that's fast becoming a thing of the past. Now corporations control the vast majority of the overall market, and it's going to get to a point that no smaller business can exist at all, it's almost at that point with all the regulations, and artificially high costs of running a business(which larger corps can mitigate, smaller business(even ones as big as OpenAI) cannot).

>since you're still relying one someone else's work and sweat as a >source material

That's largely debatable TBH. I mean, technically anyone that doesn't build their programs in binary, are relying on someone else's work and sweat as  source material. 

>Plus, it's fully ethical, since it's my sweat I had to pour into this.

TBH, I'm not suggesting that people pull the rug out from under up-and-coming successful programmers, and steal their ideas in order to plummet them into obscurity under your feet. 

It's more the concept of taking ideas or concepts that are under-realized, and making something of them. I only suggested the practice of altering what's taken in order to avoid the code-Karens out there that'll be so possessive of their code (despite not putting the work in to bring it to it's full potential), that they ruin the potential for something better. Cuz in the end, it's about the majority. 

I mean, maybe not even necessarily that they will make something 'better', but that they could make something that works for a different subset of people. Maybe it'll be coded to function better on different hardware, or have it's own unique features. 

But, yea, by no means am I suggesting, copy/paste, fandangle with ChatGPT, slap a new name on it, and add a price tag. That'd be downright dirty.  

>this thread goes really off-topic

NGL, as someone that's autistic, and therefore, has a lot more to say than the average person, I've always hated that phrase. Like, Bob forbid the expansion of a conversation beyond it's root topic. It's almost like we're humans and actually like to communicate or something.. Yuck! 

>if you care about not violating others' work licensing terms and >conditions

Well, short of the 'copy-paste' hypothetical I listed above, I'm really not concerned about that stuff at all, most of the legal system was made to protect the wealthy, and their assets. So long as what you do doesn't harm the little guy, I say, have atter. Cuz nothing should get in the way of variety, and non-corporate-driven progress.

**Comment by SpacingBat3** [comment]
> I mean, technically anyone that doesn't build their programs in binary, are relying on someone else's work and sweat as source material.

Isn't that to be the case? I'm not sure how this can be debatable, it's like you suggest forks can be freely re-licensed after some improvements were done, even violating someone else's rights and will. I really don't see how binary/non-binary stuff really changes anything, distributing stuff that relies on others' work requires following under their terms conditions. GPL proves how strong that rule can be. When you publish code and assets that you made, you usually publish them all stripped from other's work (libraries, dependencies), hence you can claim for it the full ownership. Any kind of approaches to find a loophole in it is not only harmful to trust into your work, but also harms the free and open source software distribution by creating invalid assumptions that you might not be able to protect the code in other way than closing it. And while FOSS gives you right, there are conditions you need to follow to use those rights both ethically and legally due to the copyright terms they're distributed upon. Large companies quite often follow this as well, there's a reason why so many applications has some kind of *open source licenses* tab or window bundled into them. So nothing really changes that.

> this thread goes really off-topic

This might have some negativity in it since some people use this in wrong context. Mine always is *since we categorize our conversation, try to find a better box for it and if there's none, consider if this is the right place to discuss this kind of topic*.

**Comment by Xephier102** [comment]
> Isn't that to be the case? I'm not sure how this can be debatable, it's like you suggest forks can be freely re-licensed after some improvements were done, even violating someone else's rights and will.

> distributing stuff that relies on others' work requires following under their terms conditions.

TBH, logistically and ethically, valid cases could be made for both sides of the argument. If we allow for IP theft, even a little, it's a slippery slide to all out anarchy. However, if we allow for systemic enforcement of IP's, that's a slippery slide to total corporate control over the market(which is close to what we're seeing in the modern day).

I suppose you're ultimately right(to an extent). But to clarify my own concerns on the subject; imagine a hypothetical alternate universe where the creator of Linux had released his OS, but added to the TOS that no one is to distribute altered versions of the code. Like, they can do whatever on their own machines, but no alternate versions of Linux are ever to be distributed. 

If you use Windows, then you may not be able to relate to this, but as it sits, there are currently at least one or two dozen Linux distros with millions of users, and each distro serves different use cases, or user preferences. In such a hypothetical case, millions of people would have been negatively affected, and all to honor the wishes of  single selfish individual. 

You see, in such cases, ethical guidelines are not so easily defined. It's quite comparable to the commonly posed moral quandary of if you were controlling a moving train, in which the brakes are out, and you are left with the choice of doing nothing, but there's 5 people tied to the tracks, so doing nothing will cause the train to kill those 5 people, but if you pull a lever, the train turns onto a different set of tracks with only one person tied to them, do ya 'choose' to kill one person, or do nothing and allow 5 to die?

>I really don't see how binary/non-binary stuff really changes anything

Do you include credits to the people that created C++/Python with every program you distribute?

>Large companies quite often follow this as well

Large companies, more commonly referred to as corporations, have a level of financial privilege that the vast majority of us will never come close to attaining in our lifetimes. So, they have the luxury of staying within the lines of the legal system (that was mostly built for/by them), while still getting anything and everything they want. If there's a company they want, and they can't get it legally, then they'll either use their resources to drive up the prices of that company's raw products.

So, that company loses value, or is driven into bankruptcy, or  they'll have a team of lawyers dissect the company and everyone in it to find ways to damage/devalue the company, etc. Honestly, there's a whole playbook on it.  In short, to corps, the legal system is nothing more than a strategic game they play to get everything they could have gotten without it. Purdue Pharma played the game for decades, and got away with effectively murdering approximately 500,000 people, and ruining the lives of millions more via the opioid epidemic , before they were shut down in 2021. 

You think silly little things like copyrights or TOS would phase corps when they can pull that off?  if they want something, they get it. Only exception may be if said contract was held by an equally powerful corporation. 

"consider if this is the right place to discuss this kind of topic"

Lol. If a Nazi were Canadian. XD.. ^^^ 
(IE: authoritarianism with a dash of politeness)

Seriously though, free speech is supposed to be a human right, though sadly, corps have managed to mostly take ownership over our free speech via the loophole that internet didn't exist when the constitution was created.

**Comment by Xephier102** [comment]
"got my point of view?"

Perhaps; basically that you excuse the thankless use of the individual Lego blocks(that were created by another), but not when someone else's Lego creation is taken, polished, copied, and redistributed. But, it is an interesting little caveat to an otherwise (mostly) solid bit of logic. I mean, for individuals, corporations still need to stop trying to own everything, and these contracts we do have to protect our creations and our dignity, should be social, not legal. 

"honestly, if I were admin, I would both hide mine and yours conversation, to keep focus on stuff that might affect the status quo of this project related to this issue ticket"

Sad, that the policing of speech is far worse in places like YouTube/Facebook/Reddit as well as the other social media, than it is in places like this. Perhaps I wouldn't be so starved of real conversation, if the other mainstream platforms weren't so bent against intellectual discourse. 

You did conveniently skip over my point regarding Linux though. Most likely I suppose because you know I have a strong point there, and either can't argue it, or know that it would take a prolonged conversation to hash it out.

But, hey, I just scrolled back to the top to remember what this thread was even about, and there's really no crime of impoliteness going on here. We are pretty much still on the original topic. The person was pointing out a potential moral/ethical conflict in regards to the use of other people's code, and that's pretty much all we've talked about. 

It's not as if it's some poor bloke waiting desperately to get an answer on some broken bit of code that's ruining their day. If that were the case, I'd actually feel bad, but in this particular case, I don't fee any feelings being hurt. It's just a harmless spot of conversation in an unlikely place. Maybe you've got lots of friends, and more important things to take care of. 

And if that's the case, I get that replying to some rando on the internet on some off, political/philosophical topic, would be seen as annoying, and perhaps an outright waste of time. But I'm not in such a socially wealthy way as of late, so this is the kinda thing I do to fill my days, and better get to know what kinda people are out there these days.

**Comment by SpacingBat3** [comment]
> You did conveniently skip over my point regarding Linux though.

Yeah, sure. Try to go into my shoes and think about everyone else with your purely hypothetical world (or consider alternative scenarios) and maybe you'll get it 😉.

---

Keeping it as short, I'm stopping this slanging match at there. No more words from me, since this conversation goes… just read it whole again and maybe you'll notice now. Maybe that'll at least make you notice it went too far, too fast into what's **terrible** example of issue thread. Definitely off-topic to development itself. + It's all resolved lol.
